Repository riscv/sail-riscv, pull requests merged in 2025-05, with the labels that each got.

#906 Fix Svbare warning.
  README.md
  config/default.json
  model/riscv_extensions.sail
Labels: will be merged

#862 Add support for Zvksh extension
  README.md
  config/default.json
  model/CMakeLists.txt
  model/arithmetic.sail
  model/riscv_extensions.sail
  model/riscv_insts_vext_utils.sail
  model/riscv_insts_zvksh.sail
  model/riscv_zvk_utils.sail
Labels: will be merged, extension

#911 Add missing riscv_sstc.sail to CMake build
  model/CMakeLists.txt
Labels: will be merged

#899 Make truncate infer its length
  model/prelude.sail
  model/riscv_fdext_regs.sail
  model/riscv_vmem_tlb.sail
Labels: will be merged

#914 Fix compilation of the Lean backend
  model/riscv_insts_vext_utils.sail
Labels: will be merged

#494 Implement callbacks for state-changing events
  c_emulator/CMakeLists.txt
  c_emulator/riscv_callbacks.cpp
  c_emulator/riscv_callbacks.h
  c_emulator/riscv_prelude.cpp
  c_emulator/riscv_prelude.h
  model/CMakeLists.txt
  model/prelude.sail
  model/riscv_callbacks.sail
  model/riscv_fdext_regs.sail
  model/riscv_insts_vext_mem.sail
  model/riscv_insts_vext_vset.sail
  model/riscv_insts_zicsr.sail
  model/riscv_mem.sail
  model/riscv_pc_access.sail
  model/riscv_regs.sail
  model/riscv_sys_control.sail
  model/riscv_types.sail
  model/riscv_vext_control.sail
  model/riscv_vext_regs.sail
  model/rvfi_dii.sail
Labels: will be merged

#861 Handle address translation for misaligned loads and stores better
  Makefile.old
  config/default.json
  doc/ReadingGuide.md
  model/CMakeLists.txt
  model/riscv_insts_aext.sail
  model/riscv_insts_base.sail
  model/riscv_insts_fext.sail
  model/riscv_insts_vext_mem.sail
  model/riscv_mem.sail
  model/riscv_termination.sail
  model/riscv_vmem_utils.sail
Labels: will be merged

#923 Add empty stubs for the state-change callbacks
  model/riscv_callbacks.sail
  model/riscv_fdext_regs.sail
  model/riscv_vext_regs.sail
Labels: will be merged

#927 Remove another rogue reference to the N extension
  model/riscv_sys_regs.sail
Labels: will be merged

#926 Remove tick_platform() and htif_tick()
  c_emulator/CMakeLists.txt
  c_emulator/riscv_sail.h
  c_emulator/riscv_sim.cpp
  model/CMakeLists.txt
  model/riscv_platform.sail
  model/riscv_step.sail
Labels: will be merged

#867 Fix macOS compilation and add to CI
  .github/workflows/compile.yml
  c_emulator/CMakeLists.txt
  sail_runtime/CMakeLists.txt
Labels: will be merged

#752 Add support for Zvkned.
  Makefile.old
  README.md
  config/default.json
  model/CMakeLists.txt
  model/riscv_extensions.sail
  model/riscv_insts_vext_utils.sail
  model/riscv_insts_zvkned.sail
  model/riscv_zvk_utils.sail
Labels: will be merged, extension

#932 Make RVFI a runtime option
  .github/workflows/compile.yml
  CMakeLists.txt
  README.md
  c_emulator/CMakeLists.txt
  c_emulator/riscv_callbacks.cpp
  c_emulator/riscv_callbacks.h
  c_emulator/riscv_config.h
  c_emulator/riscv_prelude.cpp
  c_emulator/riscv_prelude.h
  c_emulator/riscv_sail.h
  c_emulator/riscv_sim.cpp
  c_emulator/rvfi_dii.cpp
  model/CMakeLists.txt
  model/prelude.sail
  model/riscv_fetch.sail
  model/riscv_fetch_rvfi.sail
  model/riscv_platform.sail
  model/riscv_step.sail
  model/riscv_step_rvfi.sail
  model/rvfi_dii.sail
Labels: will be merged

#937 Define and use a width type for memory widths.
  .github/workflows/compile.yml
  model/riscv_insts_vext_mem.sail
  model/riscv_sys_regs.sail
  model/riscv_types.sail
  model/riscv_vmem_utils.sail
Labels: will be merged

#946 Add mstatush to csr_name_map
  model/riscv_sys_regs.sail
Labels: will be merged

#942 Fix vreg write print output
  c_emulator/riscv_callbacks.cpp
  c_emulator/riscv_sail.h
Labels: will be merged

#928 Add config option to trap on sfence.vma if virt mem not supported
  config/default.json
  model/riscv_insts_base.sail
Labels: configuration, will be merged

#949 Prevent build failures with CMake versions < 3.24.
  CMakeLists.txt
Labels: will be merged

#943 Fix x and f register write print output
  c_emulator/riscv_callbacks.cpp
  c_emulator/riscv_sail.h
Labels: will be merged

#953 Fix xepc interaction with compressed extensions
  model/riscv_insts_zcf.sail
  model/riscv_sys_regs.sail
Labels: will be merged

#921 Add option to print abi or architectural register names in trace and disassembly
  c_emulator/riscv_callbacks.cpp
  c_emulator/riscv_callbacks.h
  c_emulator/riscv_config.h
  c_emulator/riscv_prelude.cpp
  c_emulator/riscv_prelude.h
  c_emulator/riscv_sim.cpp
  model/prelude.sail
  model/riscv_callbacks.sail
  model/riscv_regs.sail
Labels: will be merged

#955 Split the Zaamo and Zalrsc extensions into separate files
  model/CMakeLists.txt
  model/riscv_insts_zaamo.sail
  model/riscv_insts_zalrsc.sail
Labels: will be merged

#957 Use existing bit counting functions
  model/arithmetic.sail
  model/riscv_insts_vext_fp_utils.sail
  model/riscv_insts_vext_utils.sail
  model/riscv_insts_zbb.sail
Labels: will be merged

#958 Use to_bits_checked() for config values
  model/main.sail
  model/riscv_platform.sail
  model/riscv_sys_regs.sail
Labels: will be merged

#961 Fix to_bits_unsafe() in PMP code
  model/riscv_pmp_control.sail
Labels: will be merged

#963 Fix to_bits_unsafe() for vector length registers
  model/riscv_sys_regs.sail
Labels: will be merged

#962 Fix to_bits_unsafe() in RVFI
  model/rvfi_dii.sail
Labels: will be merged

#964 Fix uses of to_bits_unsafe for bit rotate and Zvbb
  model/prelude.sail
  model/riscv_insts_zvbb.sail
Labels: will be merged

#968 Use correct register prefix in `freg_write_callback`
  c_emulator/riscv_callbacks.cpp
Labels: will be merged

#875 Use result type for TR_Result instead of union
  model/riscv_fetch.sail
  model/riscv_fetch_rvfi.sail
  model/riscv_insts_zaamo.sail
  model/riscv_insts_zicbom.sail
  model/riscv_insts_zicboz.sail
  model/riscv_vmem.sail
  model/riscv_vmem_utils.sail
Labels: will be merged

#904 Make Zicsr extension configurable
  config/default.json
  model/riscv_extensions.sail
  model/riscv_fdext_control.sail
  model/riscv_insts_zicsr.sail
  model/riscv_sys_regs.sail
  model/riscv_vext_control.sail
  model/riscv_zicntr_control.sail
  model/riscv_zihpm.sail
Labels: configuration, will be merged, extension

#975 Fix lean currentlyEnabled termination issue introduced by #904
  model/riscv_termination.sail
Labels: will be merged

#973 fix: maybe_vmask() should not be prefixed with sep()
  model/riscv_insts_zvbb.sail
Labels: will be merged

#974 fix: separator after mnemonic must be spc() not sep()
  model/riscv_insts_zvkned.sail
  model/riscv_insts_zvknhab.sail
Labels: will be merged

#970 Fix printf in first party test
  test/first_party/src/common/runtime.c
Labels: will be merged

#980 fix: c.sh has operands reversed
  model/riscv_insts_zcb.sail
Labels: will be merged

#981 fix: c.sw,c.sd have assembly operands reversed, missing parens
  model/riscv_insts_zca.sail
Labels: will be merged

#983 fix: fcvtmod.w.d requires explicit "rtz"
  model/riscv_insts_zfa.sail
Labels: will be merged

#984 fix: fence.tso has no operands
  model/riscv_insts_base.sail
Labels: will be merged

#979 Remove regidx_to_regno functions etc.
  model/riscv_fdext_regs.sail
  model/riscv_regs.sail
  model/riscv_types.sail
Labels: will be merged

#988 Move the `get_config_` function out of `riscv_sim.cpp`.
  c_emulator/CMakeLists.txt
  c_emulator/config_utils.cpp
  c_emulator/config_utils.h
  c_emulator/riscv_sim.cpp
Labels: will be merged

#819 Add support for Zvkg extension
  README.md
  config/default.json
  model/CMakeLists.txt
  model/arithmetic.sail
  model/riscv_extensions.sail
  model/riscv_insts_zvkg.sail
Labels: will be merged, extension

#989 Include climits in riscv_sim.cpp
  c_emulator/riscv_sim.cpp
Labels: will be merged

#987 Lean CI: use the latest version of sail
  .github/workflows/compile-lean.yml
Labels: will be merged

#996 Fix handling of .aqrl in assembly mapping
  model/riscv_insts_base.sail
  model/riscv_insts_zaamo.sail
  model/riscv_insts_zalrsc.sail
Labels: will be merged
