Repository riscv/sail-riscv, pull requests merged in 2025-08, with the labels that each got.

#1187 Fix validation message.
  c_emulator/riscv_sim.cpp
Labels: will be merged

#1188 Remove unused getopt code.
  c_emulator/riscv_sim.cpp
Labels: will be merged

#1142 Add a release notes file to docs.
  cmake/packaging.cmake
  doc/ChangeLog.md
Labels: will be merged

#646 Support for the E base architecture
  README.md
  c_emulator/riscv_callbacks.cpp
  c_emulator/riscv_callbacks.h
  c_emulator/riscv_callbacks_if.h
  c_emulator/riscv_callbacks_log.cpp
  c_emulator/riscv_callbacks_log.h
  c_emulator/riscv_callbacks_rvfi.cpp
  c_emulator/riscv_callbacks_rvfi.h
  config/rv32d.json
  config/rv64d.json
  doc/ChangeLog.md
  model/riscv_regs.sail
  model/riscv_sys_control.sail
  model/riscv_sys_regs.sail
  model/riscv_types.sail
Labels: will be merged, extension

#1197 Remove duplicate config_print checks
  c_emulator/riscv_prelude.cpp
  c_emulator/riscv_prelude.h
  model/prelude.sail
  model/riscv_platform.sail
  model/riscv_step.sail
  model/riscv_sys_control.sail
Labels: will be merged

#1211 Run full testsuite on PRs with `run-full-tests` label
  .github/workflows/run-full-tests.yml
Labels: will be merged, run-full-tests

#1208 Add the Zihintntl and Zihintpause extensions.
  README.md
  config/rv32d.json
  config/rv64d.json
  doc/ChangeLog.md
  model/riscv.sail_project
  model/riscv_extensions.sail
  model/riscv_insts_zihintntl.sail
  model/riscv_insts_zihintpause.sail
  model/riscv_zihintntl_types.sail
Labels: will be merged, extension

#1177 Load ELFs via ELFIO and add symbols to the trace output
  CMakeLists.txt
  c_emulator/CMakeLists.txt
  c_emulator/elf_loader.cpp
  c_emulator/elf_loader.h
  c_emulator/riscv_platform.cpp
  c_emulator/riscv_prelude.cpp
  c_emulator/riscv_prelude.h
  c_emulator/riscv_sim.cpp
  c_emulator/symbol_table.cpp
  c_emulator/symbol_table.h
  cmake/packaging.cmake
  dependencies/CMakeLists.txt
  dependencies/elfio/CMakeLists.txt
  dependencies/elfio/LICENSE.txt
  dependencies/elfio/README.md
  dependencies/elfio/cmake/elfioConfig.cmake.in
  dependencies/elfio/elfio/elf_types.hpp
  dependencies/elfio/elfio/elfio.hpp
  dependencies/elfio/elfio/elfio_array.hpp
  dependencies/elfio/elfio/elfio_dump.hpp
  dependencies/elfio/elfio/elfio_dynamic.hpp
  dependencies/elfio/elfio/elfio_header.hpp
  dependencies/elfio/elfio/elfio_modinfo.hpp
  dependencies/elfio/elfio/elfio_note.hpp
  dependencies/elfio/elfio/elfio_relocation.hpp
  dependencies/elfio/elfio/elfio_section.hpp
  dependencies/elfio/elfio/elfio_segment.hpp
  dependencies/elfio/elfio/elfio_strings.hpp
  dependencies/elfio/elfio/elfio_symbols.hpp
  dependencies/elfio/elfio/elfio_utils.hpp
  dependencies/elfio/elfio/elfio_version.hpp
  dependencies/elfio/elfio/elfio_versym.hpp
  doc/ChangeLog.md
  model/prelude.sail
  model/riscv_step.sail
Labels: will be merged

#1221 Rename CLIUtils directory to CLI11
  cmake/packaging.cmake
  dependencies/CLI11/CLI11.hpp
  dependencies/CLI11/CMakeLists.txt
  dependencies/CLI11/LICENSE
  dependencies/CMakeLists.txt
Labels: will be merged

#1223 Simplify check_PTE_permission
  model/riscv_vmem_pte.sail
Labels: will be merged

#1203 Simplify riscv_insts_vext_mem's function signatures
  model/riscv_insts_vext_mem.sail
Labels: will be merged

#1206 Remove unused `ext_control_check_addr` hook function.
  model/riscv_addr_checks.sail
Labels: will be merged

#1207 Remove unused `ext_check_phys_mem_{read,write}` hooks.
  model/riscv_addr_checks.sail
  model/riscv_addr_checks_common.sail
  model/riscv_mem.sail
Labels: refactor, will be merged

#1224 Split PTE privilege and access checks
  model/riscv_types.sail
  model/riscv_vmem_pte.sail
Labels: will be merged

#1230 Fix location of generated configs for install.
  config/CMakeLists.txt
Labels: will be merged

#1237 Remove unused tuple in match of `exception_handler`.
  model/riscv_sys_control.sail
Labels: will be merged
