Repository riscv/sail-riscv, pull requests merged in 2025-07, with the labels that each got.

#1114 Add config flags to control PMP address mode support
  config/rv32d.json
  config/rv64d.json
  model/riscv_pmp_control.sail
  model/riscv_pmp_regs.sail
  model/riscv_validate_config.sail
Labels: will be merged

#1115 Replace exit codes with EXIT_SUCCESS/EXIT_FAILURE constants
  c_emulator/config_utils.cpp
  c_emulator/riscv_sim.cpp
  c_emulator/rvfi_dii.cpp
Labels: will be merged

#1106 Rename `ast` to `instruction`
  README.md
  doc/ReadingGuide.md
  model/CMakeLists.txt
  model/riscv_decode_ext.sail
  model/riscv_insts_base.sail
  model/riscv_insts_begin.sail
  model/riscv_insts_dext.sail
  model/riscv_insts_end.sail
  model/riscv_insts_fext.sail
  model/riscv_insts_mext.sail
  model/riscv_insts_reserved_fence.sail
  model/riscv_insts_rmem.sail
  model/riscv_insts_svinval.sail
  model/riscv_insts_vext_arith.sail
  model/riscv_insts_vext_fp.sail
  model/riscv_insts_vext_fp_red.sail
  model/riscv_insts_vext_fp_vm.sail
  model/riscv_insts_vext_mask.sail
  model/riscv_insts_vext_mem.sail
  model/riscv_insts_vext_red.sail
  model/riscv_insts_vext_vm.sail
  model/riscv_insts_vext_vset.sail
  model/riscv_insts_zaamo.sail
  model/riscv_insts_zalrsc.sail
  model/riscv_insts_zawrs.sail
  model/riscv_insts_zba.sail
  model/riscv_insts_zbb.sail
  model/riscv_insts_zbc.sail
  model/riscv_insts_zbkb.sail
  model/riscv_insts_zbkx.sail
  model/riscv_insts_zbs.sail
  model/riscv_insts_zca.sail
  model/riscv_insts_zcb.sail
  model/riscv_insts_zcd.sail
  model/riscv_insts_zcf.sail
  model/riscv_insts_zcmop.sail
  model/riscv_insts_zfa.sail
  model/riscv_insts_zfh.sail
  model/riscv_insts_zicbom.sail
  model/riscv_insts_zicboz.sail
  model/riscv_insts_zicond.sail
  model/riscv_insts_zicsr.sail
  model/riscv_insts_zifencei.sail
  model/riscv_insts_zimop.sail
  model/riscv_insts_zkn.sail
  model/riscv_insts_zks.sail
  model/riscv_insts_zvbb.sail
  model/riscv_insts_zvbc.sail
  model/riscv_insts_zvkg.sail
  model/riscv_insts_zvkned.sail
  model/riscv_insts_zvknhab.sail
  model/riscv_insts_zvksed.sail
  model/riscv_insts_zvksh.sail
  model/riscv_step.sail
  model/riscv_termination.sail
Labels: will be merged

#918 Add the config schema to the build.
  model/CMakeLists.txt
Labels: will be merged

#1108 Use newtype cfregidx for compressed floating point register indices
  model/riscv_fdext_regs.sail
  model/riscv_insts_zcd.sail
  model/riscv_insts_zcf.sail
Labels: will be merged

#1096 Auto-enable Vector Crypto superset extensions (Zvkn, Zvknc, Zvkng, Zvks, Zvksc, Zvksg)
  README.md
  model/riscv_extensions.sail
  model/riscv_termination.sail
Labels: will be merged

#1127 Fix mhpmeventnh CSR name mappings
  model/riscv_sscofpmf.sail
Labels: will be merged

#1118 Test SMT properties in CI
  model/CMakeLists.txt
Labels: will be merged

#1119 Reduce duplication in Zba
  model/riscv_insts_zba.sail
  model/riscv_insts_zcb.sail
  model/riscv_types.sail
Labels: will be merged

#1120 Merge float load/store encdec clauses
  model/riscv_insts_fext.sail
Labels: will be merged

#1123 Build libgmp as position independent code
  CMakeLists.txt
Labels: will be merged

#1124 Allow `write_CSR` to indicate an illegal instruction trap.
  model/riscv_csr_begin.sail
  model/riscv_fdext_control.sail
  model/riscv_insts_zicsr.sail
  model/riscv_pmp_regs.sail
  model/riscv_smcntrpmf.sail
  model/riscv_sscofpmf.sail
  model/riscv_sstc.sail
  model/riscv_sys_exceptions.sail
  model/riscv_sys_regs.sail
  model/riscv_vext_control.sail
  model/riscv_vmem.sail
  model/riscv_zicntr_control.sail
  model/riscv_zihpm.sail
  model/riscv_zkr_control.sail
Labels: refactor, will be merged

#1128 Fix CSR trace output to print correct width based on XLEN
  c_emulator/riscv_callbacks.cpp
Labels: will be merged

#1130 adapt isla_footprint to the init_model signature change
  model/main.sail
Labels: will be merged

#1117 Rationalize the location of vector CSRs and their handling.
  model/riscv_sys_regs.sail
  model/riscv_vext_control.sail
  model/riscv_vext_regs.sail
Labels: will be merged

#285 Add Zacas (atomic compare and swap) extension
  README.md
  config/rv32d.json
  config/rv64d.json
  model/riscv_extensions.sail
  model/riscv_insts_zaamo.sail
  model/riscv_regs.sail
  model/riscv_termination.sail
  model/riscv_types.sail
Labels: will be merged, extension

#887 Add a project version and build information to the simulator.
  .github/workflows/compile.yml
  CMakeLists.txt
  c_emulator/CMakeLists.txt
  c_emulator/riscv_sim.cpp
  c_emulator/sail_riscv_version.cpp.in
  c_emulator/sail_riscv_version.h
  cmake/project_version.cmake
Labels: will be merged

#1143 Fix number of defined `pmpcfg` CSRs
  model/riscv_pmp_regs.sail
Labels: will be merged

#1145 Remove a now unused compiler flag check.
  CMakeLists.txt
Labels: will be merged

#1147 Add README.md for berkeley-softfloat-3 library
  dependencies/softfloat/berkeley-softfloat-3/README.md
Labels: will be merged

#1144 Add config and doc files to CPack install.
  CMakeLists.txt
  c_emulator/CMakeLists.txt
  cmake/packaging.cmake
  config/CMakeLists.txt
  model/CMakeLists.txt
Labels: will be merged

#1140 Move privilege-based CSR access into scattered is_CSR_accessible function
  model/riscv_csr_begin.sail
  model/riscv_csr_end.sail
  model/riscv_fdext_control.sail
  model/riscv_pmp_regs.sail
  model/riscv_smcntrpmf.sail
  model/riscv_sscofpmf.sail
  model/riscv_sstc.sail
  model/riscv_sys_control.sail
  model/riscv_sys_exceptions.sail
  model/riscv_sys_regs.sail
  model/riscv_vext_regs.sail
  model/riscv_vmem.sail
  model/riscv_zicntr_control.sail
  model/riscv_zihpm.sail
  model/riscv_zkr_control.sail
Labels: will be merged

#1153 Update release workflow
  .github/workflows/release.yml
Labels: will be merged

#1010 Support generating assembly for reserved vtypes
  model/riscv_insts_vext_vset.sail
Labels: will be merged

#572 Add sail_project file to modularise the specification
  model/CMakeLists.txt
  model/riscv.sail_project
Labels: tgmm-agenda, will be merged

#1168 Simplify model/CMakeLists.txt by removing `variant`
  model/CMakeLists.txt
Labels: will be merged

#1169 Update Sail RISC-V Tests download URL
  test/CMakeLists.txt
  test/README.md
Labels: will be merged

#1160 Extract jumping to a PC into a function
  model/riscv_insts_base.sail
  model/riscv_jalr_seq.sail
Labels: will be merged

#1166 Simplify vector code when calling read_vmask
  model/riscv_insts_vext_arith.sail
  model/riscv_insts_vext_fp.sail
Labels: will be merged

#1167 Fix immediate signedness bug in NISTYPE/NITYPE
  model/riscv_insts_vext_arith.sail
Labels: will be merged

#1175 Remove `BitStr()`, `bit_str()` and use native `bits_str()` instead
  model/prelude.sail
  model/riscv_freg_type.sail
  model/riscv_platform.sail
  model/riscv_reg_type.sail
  model/riscv_step.sail
  model/riscv_sys_control.sail
  model/riscv_types.sail
Labels: will be merged

#1146 Decouple callbacks impl from model by introducing callback interface
  c_emulator/CMakeLists.txt
  c_emulator/riscv_callbacks.cpp
  c_emulator/riscv_callbacks.h
  c_emulator/riscv_callbacks_if.h
  c_emulator/riscv_callbacks_log.cpp
  c_emulator/riscv_callbacks_log.h
  c_emulator/riscv_callbacks_rvfi.cpp
  c_emulator/riscv_callbacks_rvfi.h
  c_emulator/riscv_sail.h
  c_emulator/riscv_sim.cpp
Labels: will be merged
