Repository riscv/sail-riscv, pull requests merged in 2025-04, with the labels that each got.

#820 Remove unused code from riscv_sim.cpp
  c_emulator/riscv_sim.cpp
Labels: will be merged

#821 Add cmake support for Rocq
  CMakeLists.txt
  coq-sail-riscv.opam
  handwritten_support/CMakeLists.txt
  handwritten_support/riscv_extras.v
  model/CMakeLists.txt
Labels: will be merged

#758 Replace ad-hoc model configuration with Sail-native configuration
  .github/workflows/compile.yml
  CMakeLists.txt
  c_emulator/CMakeLists.txt
  c_emulator/riscv_platform.cpp
  c_emulator/riscv_platform.h
  c_emulator/riscv_platform_impl.cpp
  c_emulator/riscv_platform_impl.h
  c_emulator/riscv_sim.cpp
  config/CMakeLists.txt
  config/default.json
  config/default_config.h.in
  model/CMakeLists.txt
  model/riscv_insts_vext_vset.sail
  model/riscv_platform.sail
  model/riscv_sys_regs.sail
  model/riscv_vlen.sail
  sail_runtime/CMakeLists.txt
  test/first_party/CMakeLists.txt
  test/riscv-tests/CMakeLists.txt
Labels: tgmm-agenda, will be merged

#826 Fix PMP test
  config/default.json
  test/first_party/CMakeLists.txt
Labels: will be merged

#828 Don't print the clang warning message if a gcc cross-compiler is found
  test/first_party/CMakeLists.txt
Labels: will be merged

#831 Remove mentions of ustatus
  model/riscv_sys_regs.sail
Labels: will be merged

#827 Update README with initial help on the new model configuration scheme.
  README.md
Labels: will be merged

#823 Rename pte_is_ptr to pte_is_non_leaf for clarity
  model/riscv_vmem.sail
  model/riscv_vmem_pte.sail
Labels: will be merged

#822 Improvements to prelude
  model/CMakeLists.txt
  model/arithmetic.sail
  model/prelude.sail
  model/riscv_insts_zbc.sail
  model/riscv_insts_zvbc.sail
Labels: will be merged

#817 Capitalize Physaddr and Virtaddr constructors
  model/prelude_mem.sail
  model/prelude_mem_addrtype.sail
  model/riscv_addr_checks.sail
  model/riscv_insts_base.sail
  model/riscv_mem.sail
  model/riscv_platform.sail
  model/riscv_pmp_control.sail
  model/riscv_step.sail
  model/riscv_sys_control.sail
  model/riscv_vmem.sail
Labels: will be merged

#829 Remove unused cli opts
  c_emulator/riscv_sim.cpp
Labels: will be merged

#833 Remove unused zeros overload
  model/prelude.sail
  model/riscv_insts_zicsr.sail
Labels: will be merged

#838 Remove executable bit from several files and add check to pre-commit
  .pre-commit-config.yaml
  model/riscv_insts_vext_fp.sail
  model/riscv_insts_vext_fp_red.sail
  model/riscv_insts_vext_fp_utils.sail
  model/riscv_insts_vext_fp_vm.sail
  model/riscv_insts_vext_mask.sail
  model/riscv_insts_vext_red.sail
  model/riscv_insts_vext_utils.sail
  model/riscv_insts_vext_vm.sail
  model/riscv_vext_control.sail
  model/riscv_vreg_type.sail
Labels: will be merged

#836 Define a reverse carry-less multiply function for cmulr instructions.
  Makefile.old
  model/arithmetic.sail
  model/riscv_insts_zbc.sail
Labels: will be merged

#800 Add enable-experimental flag for unratified extensions
  README.md
  c_emulator/riscv_platform.cpp
  c_emulator/riscv_platform.h
  c_emulator/riscv_platform_impl.cpp
  c_emulator/riscv_platform_impl.h
  c_emulator/riscv_sim.cpp
  model/prelude.sail
Labels: will be merged

#842 Add CI to produce and compile the Lean backend
  .github/workflows/compile-lean.yml
  model/CMakeLists.txt
Labels: will be merged

#846 Update Isabelle and Rocq support
  CMakeLists.txt
  Makefile.old
  README.md
  handwritten_support/ROOT
  handwritten_support/ROOT.in
  handwritten_support/mem_metadata.lem
  handwritten_support/riscv_extras.lem
  handwritten_support/riscv_extras.v
  handwritten_support/riscv_extras_fdext.lem
  model/CMakeLists.txt
  sail_runtime/CMakeLists.txt
Labels: will be merged

#840 Use correct effective privilege for cbo.clean/inval
  model/riscv_insts_zicbom.sail
Labels: will be merged

#845 Add configuration options for (almost) all supported extensions
  config/default.json
  model/riscv_extensions.sail
  model/riscv_fdext_control.sail
  model/riscv_insts_aext.sail
  model/riscv_insts_base.sail
  model/riscv_insts_dext.sail
  model/riscv_insts_fext.sail
  model/riscv_insts_mext.sail
  model/riscv_insts_zba.sail
  model/riscv_insts_zbb.sail
  model/riscv_insts_zbc.sail
  model/riscv_insts_zbkx.sail
  model/riscv_insts_zbs.sail
  model/riscv_insts_zcd.sail
  model/riscv_insts_zcf.sail
  model/riscv_insts_zcmop.sail
  model/riscv_insts_zfa.sail
  model/riscv_insts_zfh.sail
  model/riscv_insts_zicond.sail
  model/riscv_insts_zifencei.sail
  model/riscv_insts_zimop.sail
  model/riscv_insts_zkn.sail
  model/riscv_insts_zks.sail
  model/riscv_insts_zvbb.sail
  model/riscv_smcntrpmf.sail
  model/riscv_sscofpmf.sail
  model/riscv_sys_control.sail
  model/riscv_sys_regs.sail
  model/riscv_vext_control.sail
  model/riscv_zicntr_control.sail
  model/riscv_zihpm.sail
  model/riscv_zkr_control.sail
Labels: will be merged

#847 Revert "Fix minstreth behaviour"
  model/riscv_step.sail
  model/riscv_sys_regs.sail
  model/riscv_zicntr_control.sail
  test/first_party/src/test_minstret.S
Labels: will be merged

#854 Enable misaligned accesses in default config for riscv-tests
  config/default.json
Labels: will be merged

#852 Fix PMP address matching
  model/riscv_pmp_control.sail
  test/first_party/CMakeLists.txt
  test/first_party/src/common/crt0.S
  test/first_party/src/test_max_pmp.c
  test/first_party/src/test_pmp_access.c
Labels: will be merged

#856 Remove reverse overload
  model/arithmetic.sail
  model/prelude.sail
  model/riscv_insts_zbkb.sail
  model/riscv_insts_zvbb.sail
Labels: will be merged

#843 Add support for Zvknha and Zvknhb extensions
  README.md
  config/default.json
  model/CMakeLists.txt
  model/riscv_extensions.sail
  model/riscv_insts_vext_utils.sail
  model/riscv_insts_zvknhab.sail
  model/riscv_zvk_utils.sail
Labels: will be merged, extension

#858 Add cmake_policy
  CMakeLists.txt
Labels: will be merged

#863 Add URL_HASH to GMP download
  CMakeLists.txt
Labels: will be merged

#837 More closely align address translation with the specification.
  model/riscv_vmem.sail
  model/riscv_vmem_pte.sail
Labels: will be merged

#868 Add prettier pre-commit hook
  .github/workflows/compile-lean.yml
  .github/workflows/compile.yml
  .github/workflows/release.yml
  .github/workflows/test-results.yml
  .pre-commit-config.yaml
  CODE_STYLE.md
  CONTRIBUTING.md
  README.md
  config/default.json
  doc/ExtendingGuide.md
  doc/ReadingGuide.md
  os-boot/README.md
  test/README.md
  test/riscv-tests/README
Labels: will be merged

#857 Add overload bits_of for virtaddr_bits and physaddr_bits
  model/prelude_mem_addrtype.sail
  model/riscv_fetch.sail
  model/riscv_fetch_rvfi.sail
  model/riscv_insts_aext.sail
  model/riscv_insts_base.sail
  model/riscv_jalr_seq.sail
  model/riscv_mem.sail
  model/riscv_vmem.sail
Labels: will be merged

#791 [Ext_V] Simplily nf type constrains
  model/riscv_insts_vext_mem.sail
  model/riscv_insts_vext_utils.sail
Labels: will be merged

#864 Update Rocq termination information and add CI
  .github/workflows/rocq.yml
  model/riscv_termination.sail
Labels: will be merged

#839 Rename the Execute access type to InstructionFetch
  model/riscv_fetch.sail
  model/riscv_fetch_rvfi.sail
  model/riscv_mem.sail
  model/riscv_platform.sail
  model/riscv_pmp_control.sail
  model/riscv_sys_regs.sail
  model/riscv_types.sail
  model/riscv_vmem.sail
  model/riscv_vmem_pte.sail
  model/riscv_vmem_ptw.sail
  model/riscv_vmem_types.sail
Labels: will be merged

#877 Rename Zfa `rs1` to `constantidx`
  model/riscv_insts_zfa.sail
Labels: will be merged

#872 Use result type instead of PTW_Result
  model/riscv_vmem.sail
Labels: will be merged

#882 CMakeLists: Add mirrors of gmp.
  CMakeLists.txt
Labels: will be merged

#865 Add termination measures to the Lean backend
  model/CMakeLists.txt
Labels: will be merged

#881 Change default instructions_per_tick to 2
  config/default.json
Labels: will be merged

#878 Remove redundant RISCV_ prefixes on internal ast nodes and enums.
  model/riscv_insts_base.sail
  model/riscv_insts_zba.sail
  model/riscv_insts_zbb.sail
  model/riscv_insts_zbc.sail
  model/riscv_insts_zbkb.sail
  model/riscv_insts_zbkx.sail
  model/riscv_insts_zbs.sail
  model/riscv_insts_zca.sail
  model/riscv_insts_zcb.sail
  model/riscv_insts_zfa.sail
  model/riscv_insts_zicbom.sail
  model/riscv_insts_zicboz.sail
  model/riscv_insts_zicond.sail
  model/riscv_jalr_rmem.sail
  model/riscv_jalr_seq.sail
  model/riscv_types.sail
Labels: will be merged

#888 Fix the '--help' option.
  c_emulator/riscv_sim.cpp
Labels: will be merged

#883 Refactor try_step() some more
  model/riscv_platform.sail
  model/riscv_step.sail
  model/riscv_step_common.sail
  model/riscv_sys_regs.sail
  model/riscv_types.sail
Labels: will be merged

#893 Update README build instructions and general cleanup
  README.md
Labels: will be merged

#897 Remove unused lrsc_width_str function
  model/riscv_insts_aext.sail
Labels: will be merged

#807 Add satp mode guard
  config/default.json
  model/riscv_extensions.sail
  model/riscv_sys_regs.sail
Labels: tgmm-agenda, configuration, will be merged

#896 Inline machine info register initialization
  model/riscv_platform.sail
  model/riscv_sys_regs.sail
Labels: will be merged

#901 Make Rocq workflow run on request.
  .github/workflows/rocq.yml
Labels: will be merged

#892 Disable htif when tohost symbol not found
  c_emulator/riscv_platform.cpp
  c_emulator/riscv_platform.h
  c_emulator/riscv_platform_impl.cpp
  c_emulator/riscv_platform_impl.h
  c_emulator/riscv_sim.cpp
  handwritten_support/RiscvExtras.lean
  handwritten_support/riscv_extras.lem
  handwritten_support/riscv_extras.v
  model/riscv_platform.sail
Labels: will be merged

#895 riscv_types cleanup
  c_emulator/riscv_platform.cpp
  c_emulator/riscv_sail.h
  c_emulator/riscv_sim.cpp
  model/riscv_insts_zbb.sail
  model/riscv_types.sail
Labels: will be merged
