Repository riscv/sail-riscv, pull requests merged in 2025-03, with the labels that each got.

#760 Fix minstreth behaviour
  model/riscv_step.sail
  model/riscv_sys_regs.sail
  model/riscv_zicntr_control.sail
Labels: will be merged

#748 store `total_insns` and `insn_limit` as `uint64_t`, not `int`
  c_emulator/riscv_sim.c
Labels: will be merged

#764 Add first party C tests
  .github/workflows/compile.yml
  CMakeLists.txt
  test/CMakeLists.txt
  test/README
  test/README.md
  test/first_party/CMakeLists.txt
  test/first_party/src/common/crt0.S
  test/first_party/src/common/encoding.h
  test/first_party/src/common/link.ld
  test/first_party/src/common/nanoprintf.c
  test/first_party/src/common/nanoprintf.h
  test/first_party/src/common/runtime.c
  test/first_party/src/common/runtime.h
  test/first_party/src/test_hello_world.c
  test/first_party/src/test_minstret.S
Labels: will be merged

#772 README updates
  README.md
Labels: will be merged

#762 Build most of the C simulator as C++
  CMakeLists.txt
  c_emulator/CMakeLists.txt
  c_emulator/riscv_platform.cpp
  c_emulator/riscv_platform.h
  c_emulator/riscv_platform_impl.cpp
  c_emulator/riscv_prelude.cpp
  c_emulator/riscv_prelude.h
  c_emulator/riscv_sail.h
  c_emulator/riscv_sim.cpp
  dependencies/softfloat/CMakeLists.txt
  sail_runtime/CMakeLists.txt
Labels: will be merged

#617 Use newtypes for register indices and numbers
  model/riscv_fdext_regs.sail
  model/riscv_freg_type.sail
  model/riscv_insts_aext.sail
  model/riscv_insts_base.sail
  model/riscv_insts_dext.sail
  model/riscv_insts_fext.sail
  model/riscv_insts_hints.sail
  model/riscv_insts_mext.sail
  model/riscv_insts_svinval.sail
  model/riscv_insts_vext_arith.sail
  model/riscv_insts_vext_fp.sail
  model/riscv_insts_vext_fp_red.sail
  model/riscv_insts_vext_fp_utils.sail
  model/riscv_insts_vext_fp_vm.sail
  model/riscv_insts_vext_mask.sail
  model/riscv_insts_vext_mem.sail
  model/riscv_insts_vext_red.sail
  model/riscv_insts_vext_utils.sail
  model/riscv_insts_vext_vm.sail
  model/riscv_insts_vext_vset.sail
  model/riscv_insts_zba.sail
  model/riscv_insts_zbb.sail
  model/riscv_insts_zbc.sail
  model/riscv_insts_zbkb.sail
  model/riscv_insts_zbkx.sail
  model/riscv_insts_zbs.sail
  model/riscv_insts_zca.sail
  model/riscv_insts_zcb.sail
  model/riscv_insts_zcd.sail
  model/riscv_insts_zcf.sail
  model/riscv_insts_zfa.sail
  model/riscv_insts_zfh.sail
  model/riscv_insts_zicbom.sail
  model/riscv_insts_zicboz.sail
  model/riscv_insts_zicond.sail
  model/riscv_insts_zicsr.sail
  model/riscv_insts_zkn.sail
  model/riscv_insts_zks.sail
  model/riscv_regs.sail
  model/riscv_types.sail
  model/riscv_vext_regs.sail
Labels: will be merged

#774 Refactor `vext_mem` remove redundant type annotations and simplify
  model/riscv_insts_aext.sail
  model/riscv_insts_base.sail
  model/riscv_insts_vext_mem.sail
Labels: will be merged

#750 Update mstatus bits guarded by privilege modes
  model/riscv_sys_regs.sail
Labels: will be merged

#802 Fix linker script for GNU ld
  test/first_party/src/common/link.ld
Labels: will be merged

#805 Fix --inst-limit
  c_emulator/riscv_sim.cpp
Labels: will be merged

#718 Improve Zicbom implementation.
  model/riscv_insts_zicbom.sail
Labels: tgmm-agenda, will be merged

#784 Move most of RVFI code into its own file.
  .clang-format
  c_emulator/CMakeLists.txt
  c_emulator/riscv_sim.cpp
  c_emulator/rvfi_dii.cpp
  c_emulator/rvfi_dii.h
Labels: will be merged

#789 Update CODE_STYLE to suggest the use of `newtype`.
  CODE_STYLE.md
Labels: will be merged

#809 Update code-style to add suggestion about formatting mapping clauses and the use of `when`.
  CODE_STYLE.md
Labels: will be merged

#813 Explicitly request C++17 support
  CMakeLists.txt
Labels: will be merged

#645 Simplify Zicsr AST
  model/riscv_insts_zicsr.sail
Labels: will be merged

#816 Ensure V context is dirtied in Zvbb instructions.
  model/riscv_insts_zvbb.sail
  model/riscv_sys_control.sail
Labels: will be merged

#814 Lean: refine sizeOf instance for extension type
  handwritten_support/RiscvExtras.lean
Labels: will be merged

#794 change all mapping guard ifs with when
  model/riscv_insts_aext.sail
  model/riscv_insts_base.sail
  model/riscv_insts_dext.sail
  model/riscv_insts_fext.sail
  model/riscv_insts_hints.sail
  model/riscv_insts_mext.sail
  model/riscv_insts_svinval.sail
  model/riscv_insts_vext_arith.sail
  model/riscv_insts_vext_fp.sail
  model/riscv_insts_vext_fp_red.sail
  model/riscv_insts_vext_fp_vm.sail
  model/riscv_insts_vext_mask.sail
  model/riscv_insts_vext_mem.sail
  model/riscv_insts_vext_red.sail
  model/riscv_insts_vext_vm.sail
  model/riscv_insts_vext_vset.sail
  model/riscv_insts_zba.sail
  model/riscv_insts_zbb.sail
  model/riscv_insts_zbc.sail
  model/riscv_insts_zbkb.sail
  model/riscv_insts_zbkx.sail
  model/riscv_insts_zbs.sail
  model/riscv_insts_zca.sail
  model/riscv_insts_zcb.sail
  model/riscv_insts_zcd.sail
  model/riscv_insts_zcf.sail
  model/riscv_insts_zfa.sail
  model/riscv_insts_zfh.sail
  model/riscv_insts_zicbom.sail
  model/riscv_insts_zicboz.sail
  model/riscv_insts_zicond.sail
  model/riscv_insts_zifencei.sail
  model/riscv_insts_zkn.sail
  model/riscv_insts_zks.sail
Labels: will be merged

#773 Fix incorrect behaviour with INT_MAX pmpaddr
  model/riscv_pmp_control.sail
  test/first_party/CMakeLists.txt
  test/first_party/src/test_max_pmp.c
Labels: will be merged

#723 Implement Zimop and Zcmop Extensions
  README.md
  model/CMakeLists.txt
  model/prelude.sail
  model/riscv_extensions.sail
  model/riscv_insts_zcmop.sail
  model/riscv_insts_zimop.sail
Labels: will be merged, extension

#778 Mandatory vsetvli and vsetivli operands
  model/riscv_insts_vext_vset.sail
Labels: will be merged

#550 Add zvbc extension
  README.md
  model/CMakeLists.txt
  model/riscv_extensions.sail
  model/riscv_insts_zvbc.sail
  model/riscv_sys_regs.sail
Labels: will be merged, extension
